// examples/vue-app/src/Counter.vue
<script setup>
import { ref } from 'vue';

const props = defineProps({
  initialCount: {
    type: Number,
    default: 0
  }
});

const count = ref(props.initialCount);

function increment() {
  count.value++;
}

function decrement() {
  count.value--;
}
</script>

<template>
  <div>
    <h1>Counter: {{ count }}</h1>
    <button @click="increment">Increment</button>
    <button @click="decrement">Decrement</button>
  </div>
</template>

// examples/solid-app/src/Counter.tsx
import { createSignal } from 'solid-js';

interface CounterProps {
  initialCount?: number;
}

export function Counter(props: CounterProps) {
  const [count, setCount] = createSignal(props.initialCount || 0);

  const increment = () => {
    setCount((c) => c + 1);
  };

  const decrement = () => {
    setCount((c) => c - 1);
  };

  return (
    <div>
      <h1>Counter: {count()}</h1>
      <button onClick={increment}>Increment</button>
      <button onClick={decrement}>Decrement</button>
    </div>
  );
}
